# fly.toml app configuration file generated for stock-manager-api-patient-cloud-8941 on 2026-03-14T07:42:05+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'stock-manager-api-patient-cloud-8941'
primary_region = 'nrt'

[build]

[env]
  DB_TYPE = 'postgres'
  DB_LOG_LEVEL = 'warn'
  GIN_MODE = 'release'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
